import type { Recipe, UserProfile } from './index';

export const mockRecipes: Recipe[] = [
    {
      id: '1',
      name: 'Velvet Sunrise',
      description: 'Classic Red Velvet base with a rich cream cheese frosting, adorned with toasted almond flakes.',
      price: 65,
      imageUrl: 'https://images.unsplash.com/photo-1616690710400-914037463098?q=80&w=800&auto=format&fit=crop',
      category: 'Birthday',
      tags: ['red velvet', 'classic'],
      rating: 4.8,
      reviews: 124,
    },
    {
      id: '2',
      name: 'Midnight Espresso',
      description: 'A dark chocolate sponge cake infused with bold espresso buttercream and a light cocoa dusting.',
      price: 72,
      imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=800&auto=format&fit=crop',
      category: 'Everyday',
      tags: ['chocolate', 'coffee'],
      rating: 4.9,
      reviews: 210,
    },
    {
        id: '3',
        name: 'Lemon Zest Delight',
        description: 'A light lemon sponge with a tangy raspberry filling, crowned with fluffy meringue peaks.',
        price: 58,
        imageUrl: 'https://images.unsplash.com/photo-1562440102-385a4a11f6e2?q=80&w=800&auto=format&fit=crop',
        category: 'Seasonal',
        tags: ['lemon', 'fruit', 'raspberry'],
        rating: 4.7,
        reviews: 98,
    },
    {
        id: '4',
        name: 'Seasonal Berry Torte',
        description: 'Delicate vanilla sponge layered with a vibrant compote of fresh, seasonal mixed berries.',
        price: 85,
        imageUrl: 'https://images.unsplash.com/photo-1626379924294-4395b4520a2e?q=80&w=800&auto=format&fit=crop',
        category: 'Wedding',
        tags: ['vanilla', 'fruit', 'berry'],
        rating: 4.9,
        reviews: 75,
    },
    {
        id: '5',
        name: 'Caramel Dream',
        description: 'Layers of moist vanilla cake, salted caramel sauce, and a silky caramel buttercream.',
        price: 68,
        imageUrl: 'https://images.unsplash.com/photo-1627834393229-4185a585f9f0?q=80&w=800&auto=format&fit=crop',
        category: 'Birthday',
        tags: ['caramel', 'vanilla'],
        rating: 4.8,
        reviews: 150,
    },
    {
        id: '6',
        name: 'Enchanted Forest',
        description: 'A rich chocolate cake with blackberry filling, decorated to resemble a mystical forest floor.',
        price: 95,
        imageUrl: 'https://images.unsplash.com/photo-1619943187895-f9901b5597a7?q=80&w=800&auto=format&fit=crop',
        category: 'Wedding',
        tags: ['chocolate', 'fruit', 'blackberry'],
        rating: 5.0,
        reviews: 45,
    },
    {
        id: '7',
        name: 'Classic Vanilla Cupcakes',
        description: 'A dozen perfectly moist vanilla cupcakes with a light and airy vanilla bean buttercream.',
        price: 45,
        imageUrl: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c8b2?q=80&w=800&auto=format&fit=crop',
        category: 'Cupcakes',
        tags: ['vanilla', 'classic'],
        rating: 4.6,
        reviews: 300,
    },
    {
        id: '8',
        name: 'Decadent Chocolate Cupcakes',
        description: 'A dozen rich, moist chocolate cupcakes topped with a fudgy chocolate ganache frosting.',
        price: 48,
        imageUrl: 'https://images.unsplash.com/photo-1607478900766-efe13248b125?q=80&w=800&auto=format&fit=crop',
        category: 'Cupcakes',
        tags: ['chocolate'],
        rating: 4.9,
        reviews: 412,
    },
    // Add more for a total of 12+
    {
        id: '9',
        name: 'Pistachio Rosewater Cake',
        description: 'Aromatic cake with ground pistachios and a hint of rosewater, layered with honey buttercream.',
        price: 75,
        imageUrl: 'https://images.unsplash.com/photo-1624303423851-c75441584288?q=80&w=800&auto=format&fit=crop',
        category: 'Everyday',
        tags: ['pistachio', 'floral'],
        rating: 4.8,
        reviews: 88,
    },
    {
        id: '10',
        name: 'Pumpkin Spice Delight',
        description: 'A seasonal favorite, moist pumpkin spice cake with a tangy cream cheese frosting.',
        price: 60,
        imageUrl: 'https://images.unsplash.com/photo-1604472002347-160756784d2f?q=80&w=800&auto=format&fit=crop',
        category: 'Seasonal',
        tags: ['pumpkin', 'spice'],
        rating: 4.7,
        reviews: 112,
    },
    {
        id: '11',
        name: 'Coconut Cream Cloud',
        description: 'Light and fluffy coconut cake with a creamy coconut filling and toasted coconut flakes.',
        price: 62,
        imageUrl: 'https://images.unsplash.com/photo-1631599314923-143d489b4f3b?q=80&w=800&auto=format&fit=crop',
        category: 'Birthday',
        tags: ['coconut', 'tropical'],
        rating: 4.8,
        reviews: 130,
    },
    {
        id: '12',
        name: 'Grand Strawberry Wedding Cake',
        description: 'A magnificent three-tiered vanilla cake with fresh strawberry filling and swiss meringue buttercream.',
        price: 350,
        imageUrl: 'https://images.unsplash.com/photo-1583344654761-d78ab84d5952?q=80&w=800&auto=format&fit=crop',
        category: 'Wedding',
        tags: ['vanilla', 'fruit', 'strawberry'],
        rating: 5.0,
        reviews: 25,
    },
    {
        id: '13',
        name: 'Neapolitan Dream',
        description: 'Layers of chocolate, vanilla, and strawberry cake, with corresponding buttercream fillings.',
        price: 78,
        imageUrl: 'https://images.unsplash.com/photo-1629813134917-a1670dec79a5?q=80&w=800&auto=format&fit=crop',
        category: 'Birthday',
        tags: ['chocolate', 'vanilla', 'strawberry'],
        rating: 4.7,
        reviews: 95,
      },
      {
        id: '14',
        name: 'Matcha Green Tea Cake',
        description: 'A delicate sponge made with high-grade matcha, layered with a light white chocolate mousse.',
        price: 70,
        imageUrl: 'https://images.unsplash.com/photo-1586522359463-502a5c3789b5?q=80&w=800&auto=format&fit=crop',
        category: 'Everyday',
        tags: ['matcha', 'tea'],
        rating: 4.6,
        reviews: 79,
      },
      {
        id: '15',
        name: 'Almond & Orange Blossom Cake',
        description: 'A gluten-free almond flour cake scented with orange blossom water, topped with candied orange slices.',
        price: 65,
        imageUrl: 'https://images.unsplash.com/photo-1630409349883-424a103c899c?q=80&w=800&auto=format&fit=crop',
        category: 'Everyday',
        tags: ['almond', 'citrus', 'gluten-free'],
        rating: 4.8,
        reviews: 63,
      },
      {
        id: '16',
        name: 'Raspberry Ripple Cupcakes',
        description: 'A dozen vanilla cupcakes with a fresh raspberry puree swirled into the batter and frosting.',
        price: 48,
        imageUrl: 'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?q=80&w=800&auto=format&fit=crop',
        category: 'Cupcakes',
        tags: ['vanilla', 'fruit', 'raspberry'],
        rating: 4.7,
        reviews: 180,
      }
  ];
  

export const mockUser: UserProfile = {
  name: 'Valued Customer',
  email: 'customer@example.com',
  lastLogin: '2024-05-20T14:30:00Z',
  stats: {
    enrolledCourses: 2,
    cakesOrdered: 14,
    favoriteFlavor: 'Chocolate',
    loyaltyPoints: 850,
  },
  orders: [
    { id: 'ORD-001', date: '2024-05-15', total: 72.00, status: 'Delivered' },
    { id: 'ORD-002', date: '2024-04-22', total: 65.00, status: 'Delivered' },
    { id: 'ORD-003', date: '2024-04-01', total: 350.00, status: 'Delivered' },
    { id: 'ORD-004', date: '2024-03-10', total: 45.00, status: 'Cancelled' },
    { id: 'ORD-005', date: '2024-02-18', total: 58.00, status: 'Delivered' },
  ],
};